# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a980d71ba0da4a4e9914ba1b83b00b87db04cf8a888e22f718760d517788b9448b70f8a6985ce13b31b445fd4ef8c0f4fdf878cea96d9e227dfc1093ee2b3df5

test:
  secret_key_base: 634c9839665acf1b23718fc199bf3ecbb0a4def562b77329eb8ee7a37c3fd1a42528dd376925ef5d54f2ae0860765c022df32e47790e7acb298204a1bff22993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
